services:
  igraph:
    build: .
    container_name: igraph
    image: igraph:latest
    volumes:
      - /home/ubuntu/serve_files:/tmp
    expose:
      - '8000'
    restart: "on-failure"
    networks:
      - farcaster-network
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - igraph
      ports:
        - "4000:4000"

networks:
  farcaster-network:
    name: farcaster-network
    external: true