services:
  openrank-graph:
    build: .
    container_name: openrank-graph
    image: openrank-graph:latest
    volumes:
      - /home/ubuntu/serve_files:/tmp
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - openrank-network

networks:
  openrank-network:
    name: openrank-network
    external: true