services:
  farcaster-graph:
    build: .
    container_name: farcaster-graph
    image: farcaster-graph:latest
    volumes:
      - /home/ubuntu/serve_files:/tmp
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          memory: 64G
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - farcaster-network

networks:
  farcaster-network:
    name: farcaster-network
    external: true