name: farcaster-graph

services:
  farcaster-graph:
    build: .
    container_name: farcaster-graph
    image: farcaster-graph:latest
    volumes:
      - /tmp:/tmp
    environment:
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"