WITH 
    q_casts AS (SELECT COUNT(1) AS casts FROM casts),
    q_chain_events AS (SELECT COUNT(1) AS chain_events FROM chain_events),
    q_fids AS (SELECT COUNT(1) AS fids FROM fids),
    q_fnames AS (SELECT COUNT(1) AS fnames FROM fnames),
    q_links AS (SELECT COUNT(1) AS links FROM links),
    q_messages AS (SELECT COUNT(1) AS messages FROM messages),
    q_reactions AS (SELECT COUNT(1) AS reactions FROM reactions),
    q_signers AS (SELECT COUNT(1) AS signers FROM signers),
    q_storage_alloc AS (SELECT COUNT(1) AS storage_alloc FROM storage_allocations),
    q_user_data AS (SELECT COUNT(1) AS user_data FROM user_data),
    q_username_proofs AS (SELECT COUNT(1) AS username_proofs FROM username_proofs),
    q_verifications AS (SELECT COUNT(1) AS verifications FROM verifications)
    
SELECT 
    q_casts.casts, 
	q_chain_events.chain_events,
    q_fids.fids, 
    q_fnames.fnames, 
    q_links.links, 
    q_messages.messages,
    q_reactions.reactions, 
	q_signers.signers,
	q_storage_alloc.storage_alloc,
	q_user_data.user_data,
	q_username_proofs.username_proofs,
	q_verifications.verifications
FROM
	q_casts, 
	q_chain_events,
    q_fids, 
	q_fnames, 
	q_links, 
	q_messages, 
	q_reactions, 
	q_signers, 
	q_storage_alloc, 
	q_user_data, 
	q_username_proofs, 
	q_verifications; 
